### ISSUE TITLE
rationale behind some particle names

### ISSUE THREAD

**Issue by emmanuelthome** [cryptobib/db#107]
hi,

I was about to submit a patch that fixes some apparently erroneous occurences of the following pattern.
```
{Amaury de} Wargny
{Arnaud de} Mesmay
{Benne de} Weger
{Daniel Santana de} Freitas
{Fabien de} Montgolfier
{Fr{\'e}d{\'e}ric de} Portzamparc
{Jeroen van de} Graaf 
{Patrice Ossona de} Mendez
{Xavier de Carn{\'e} de} Carnavalet
{Ronald de} Wolf
```

which, I think, are all wrong except if authors have the unusual demand that their particle belong to their first name. While these forms do correctly sort the authors at, say, W for 'de Wargny', they do so by stripping off the particle in an abbreviated author entry.

However I noticed that there were manual edits to the database to specificallly enforce some of the entries above. (the last one in particular).

Was there a particular rationale that I could have missed ?

**Comment by michelabdalla** [comment]
Some of these entries follow the authors' preferences. This is the case, for instance, for {Jeroen van de} Graaf.  In other cases, it's probably a mistake that I introduced in the past that needs to be corrected. In my opinion, the best way to proceed is to first check the last name as they appear in the actual proceedings.

**Comment by ludopulles** [comment]
Let's take `Jeroen van de Graaf` as an example. There seem to be 3 ways to specify this name:

1. `{Jeroen van de} Graaf`,
2. `Jeroen {van de Graaf}`,
3. `Jeroen van de Graaf`.

My commit 84a1d1b4cc4de5b95694be122eb2df8e2418e893 (as part of #227 ) actually introduced some errors regarding this discussion. There is inconsistency using formats 1 and 2: "{Ronald de} Wolf" (e.g. FOCS:SinWol19) and "Ronald {de Wolf}" (e.g. FOCS:ApedeW20).

Note that format 1 (`{Jeroen van de} Graaf`) has the bad effect to be written as "Graaf, J." (completely drops the von-component), when the [splncs04.bst file from the LNCS class](https://resource-cms.springernature.com/springer-cms/rest/v1/content/19238648/data/v7) is used.

On the other hand, using format 2 (`Jeroen {van de Graaf}`) has another bad effect when using the default alpha.bst built-in bibliography style: `[van]` (or even worse: `[de ]`) is the abbreviation, and it is sorted at `v` instead of `G`.

I believe the best format is actually format 3 (`Jeroen van de Graaf`). With `\bibliographystyle{alpha}`, one gets `[vdG] Jeroen van de Graaf...`, while with `\bibliographystyle{splncs04}`, one gets `van de Graaf, J.` sorted at `G`.

Now the remaining issue that `\bibliographystyle{alpha}` doesn't sort correctly. However, one can fix this by using a fix similar to https://tex.stackexchange.com/a/108466 , namely, if one is inclined to put the effort in, they can use [a custom bibliography style different](https://gist.github.com/ludopulles/9bf56e400ae28a03a00aa0f33849584a) from the default `alpha.bst` with the following diff:
```bash
$ diff /usr/share/texmf-dist/bibtex/bst/base/alpha.bst dutchalpha.bst 
1066c1066
<       s nameptr "{vv{ } }{ll{ }}{  ff{ }}{  jj{ }}" format.name$ 't :=
---
>       s nameptr "{ll{ }}{ vv{ }}{  ff{ }}{  jj{ }}" format.name$ 't :=
1154,1156d1153
<   sort.label
<   "    "
<   *
1171d1167
<   *
```
(indeed not only sort.format.names needs changes, also the presort function should not sort on label as this would put van de Graaf at `v` back again.)

Test file:
```tex
\documentclass{article}
\begin{filecontents*}{test.bib}
	@misc{C, author="CCC CCC", title="TEST"}
	@misc{M, author="MMM MMM", title="TEST"}
	@misc{van, author="Test van AAA", title="TEST", year=2023}
	@misc{vander, author="Test van der AAA", title="TEST"}
	@misc{de, author="Test de AAA", title="TEST"}
	@misc{van2, author="Test van AAA", title="ATEST", year=2023}
	@misc{vander2, author="Test van der AAA", title="ATEST"}
	@misc{de2, author="Test de AAA", title="ATEST"}
	@misc{jvdg, author="Jeroen van de Graaf", title="Testing this"}
\end{filecontents*}
\begin{document}
\cite{M,C,de,van,vander,de2,van2,vander2,jvdg}
\bibliographystyle{dutchalpha}
\bibliography{test}
\end{document}
```
This gives the following PDF:
![sorted-references](https://github.com/cryptobib/db/assets/5180577/ce7d3188-4d30-466a-b5b7-4d4c06fe4068)

If format 3 is the preferred format, commit 84a1d1b4cc4de5b95694be122eb2df8e2418e893 can be reverted. However, then still some of the names in the initial issue message above (and possibly many more) appear inconsistent.

**Comment by emmanuelthome** [comment]
I also think that in principle, format 3 should be correct (see also item 18 in /usr/share/doc/texlive-doc/bibtex/base/btxdoc.pdf ; there are other ways to correctly let bibtex understand what are the "von", "last", "first", and "Jr" parts of a name). Unfortunately, as you point out, the default bibtex styles quite oddly sort with the "von" part included. Unless I'm mistaken, in many languages this is incorrect, but in others this is the way to go. I haven't precisely researched which, though.

I'm not sure about the right course of action, to be honest. When the authors ask their name be sorted at their particle initial, one option is to include the particle in the "last" part of the name explicitly. Something like `{von Last}, Jr, First` makes bibtex think that this name has no "von" part, and allows the particle sorting on a case by case basis. But it has the (possibly) undesired side effect of keeping "von" (literally) as the abbreviated key in an alpha.bst-style bibliography.

Most of the choices I pointed out in my original message are just wrong, but the "right" way to fix them isn't entirely clear.

**Comment by ludopulles** [comment]
I would be interested to learn about any language that sorts on "von"-prefix. Note that in Belgium there is not really a "von"-prefix because it gets capitalized, e.g. "Gilles Van Assche" is sorted at V [1]. I believe that many of the authors have indicated a preference like "{Jeroen van de} Graaf" just because the default bibtex-sorting is incorrect.

The best way forward I would say is to have the names correct in LaTeX, and suggest users to use a correct bibtex style that doesn't sort by "von" prefix. However, it's a cumbersome task to carefully go over all the names to fix them, and I don't expect myself to do this soon (as ideally you want to automate this with some python script like pybtex)...

[1] https://zichtbaarnederlands.nl/en/spelling/dutch_belgian_surnames

**Comment by michelabdalla** [comment]
hi @ludopulles, thank you for going through the trouble of fixing these entries. One of the reasons for the inconsistencies in the present bib files is because we tried Ito follow the indexing used in the actual papers.  And for several of these papers (likely the majority), dutch last names get indexed based on the "von"-prefix.

In some cases, the authors themselves have contacted us to request not using the "von"-prefixes and this is why there were different entries for those.

In any case, I will merge this PR. 

@ludopulles the current PR did not change the labels for the modified entries. Would it be possible for you to change those in another PR?

**Comment by ludopulles** [comment]
Awesome :). I will make a pull request for my branch fix-252 soon!
